env:
  repo:              "https://github.com/farrukh90/artemis.git"
  app_version:       "2.0.0"
  repo_region:       "us-central1"
  project_id:        "project-infrastructure-388501"
  app_name:          "artemis"
  tag_new_version:   "${GITHUB_SHA}"


name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      



      - name: Clone a repo
        run: |
          git clone "${{ env.repo }}"


      - name: Switch branch
        working-directory: ${{ env.app_name }}
        run: |
          git checkout "${{ env.app_version }}"
          ls -l

        - name: Build Image
        working-directory: ${{ env.app_name }}
        run: |
          docker build -t ${{ env.app_name }}:${{ env.app_version }}   . 


      # Runs a set of commands using the runners shell
      - name: Tag Image
        working-directory: ${{ env.app_name }}
        run: |
          docker image tag ${{ env.app_name }}:${{ env.app_version }} ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.app_version }}     


      # Authenticate to GCP
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'


      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  ${{ env.repo_region }}-docker.pkg.dev


      - name: Docker push
        working-directory: ${{ env.app_name }}
        run: |
          docker push  ${{ env.repo_region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.app_name }}/${{ env.app_name }}:${{ env.tag_new_version }}  